---
- name: Test ISPConfig Server ISPConfig Audit Testing
  hosts: ispconfig.example.com # Your server goes here
  become: true

  tasks:
    - name: Debug variable paths
      ansible.builtin.debug:
        msg:
          - "Playbook dir: {{ playbook_dir }}"
          - "Inventory dir: {{ inventory_dir }}"
          - "project_root: {{ inventory_dir }}"
          - "ansible_config_file: {{ ansible_config_file }}"

    - name: Ensure ansible temp directory exists with proper permissions
      become: true
      ansible.builtin.file:
        path: /tmp/ansible-tmp
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Run ISPConfig Configuration Security Audit
      ansible.builtin.include_role:
        name: jackaltx.solti_ensemble.claude_sectest
      vars:
        audit_directory: /opt/audit/ispconfig-audit
        audit_script_filename: ispconfig-audit.sh
        audit_retention_commits: 10
        audit_local_directory: ~/audit
        audit_output_filename_root: ispconfig-config
        audit_output_filename: "{{ audit_output_filename_root }}.json"

    # Required for BOM audit database access
    - name: Install Python MySQL library for BOM audit
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Run ISPConfig Database BOM Audit
      ansible.builtin.include_role:
        name: jackaltx.solti_ensemble.claude_sectest
      vars:
        audit_directory: /opt/audit/ispconfig-bom-audit
        audit_script_filename: ispconfig-bom-audit.sh
        audit_retention_commits: 10
        audit_local_directory: ~/audit
        audit_output_filename_root: ispconfig-bom-config
        audit_output_filename: "{{ audit_output_filename_root }}.json"

    - name: Run ISPConfig Named Audit
      ansible.builtin.include_role:
        name: jackaltx.solti_ensemble.claude_sectest
      vars:
        audit_directory: /opt/audit/ispconfig-named-audit
        audit_script_filename: ispconfig-named-audit.sh
        audit_retention_commits: 10
        audit_local_directory: ~/audit
        audit_output_filename_root: ispconfig-named-audit
        audit_output_filename: "{{ audit_output_filename_root }}.json"

    - name: Run ISPConfig Fail2Ban Audit
      ansible.builtin.include_role:
        name: jackaltx.solti_ensemble.claude_sectest
      vars:
        audit_directory: /opt/audit/fail2ban-audit
        audit_script_filename: fail2ban-audit.sh
        audit_retention_commits: 10
        audit_local_directory: ~/audit
        audit_output_filename_root: fail2ban-audit
        audit_output_filename: "{{ audit_output_filename_root }}.json"
