---
- name: Manage MariaDB packages for Debian
  apt:
    name: "{{ mariadb_packages }}"
    state: "{{ mariadb_state }}"
    update_cache: yes
    autoremove: "{{ mariadb_state == 'absent' }}"
    purge: "{{ mariadb_state == 'absent' }}"
