---
- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: localhost
    login_unix_socket: /run/mysqld/mysqld.sock
    check_implicit_admin: true
  ignore_errors: true

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: localhost
    login_unix_socket: /run/mysqld/mysqld.sock
    check_implicit_admin: true
  ignore_errors: true

- name: Remove remote root access
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: localhost
    login_unix_socket: /run/mysqld/mysqld.sock
    check_implicit_admin: true
  with_items:
    - "%"
    - "::1"
    - "127.0.0.1"
    - "localhost.localdomain"
  when: item != 'localhost'
  ignore_errors: true
