---
# Debian-specific variables for Matrix Synapse

matrix_package_name: matrix-synapse-py3
matrix_keyring_package: matrix-org-archive-keyring

matrix_repo_url: "https://packages.matrix.org/debian/"
matrix_repo_key_url: "https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg"

matrix_config_dir: /etc/matrix-synapse
matrix_config_file: "{{ matrix_config_dir }}/homeserver.yaml"
matrix_config_d_dir: "{{ matrix_config_dir }}/conf.d"
matrix_data_dir: /var/lib/matrix-synapse
matrix_signing_key: "{{ matrix_config_dir }}/homeserver.signing.key"

matrix_service_name: matrix-synapse
matrix_venv_path: /opt/venvs/matrix-synapse
