---
galaxy_info:
  role_name: wireguard
  author: Your Organization
  description: Wireguard VPN client installation and configuration
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - networking
    - security
    - vpn
    - wireguard
    - system