---
- name: Include present tasks
  ansible.builtin.include_tasks: present.yml
  when: wireguard_state == "present"
  tags:
    - wireguard
    - wireguard:config
    - wireguard:install

- name: Include absent tasks
  ansible.builtin.include_tasks: absent.yml
  when: wireguard_state == "absent"
  tags:
    - wireguard
    - wireguard:remove